# Sidebar navigation

- label: Grase Hotspot
  items:
  - label: 'About'
    link: '/about'
  - label: 'Github'
    link: https://github.com/GraseHotspot/grase-www-portal

- label: Support
  items:
    - label: Mailing List
      link: '/support/mailing-list'

- label: Docs
  items:
    - label: Hardware Setup
      link: '/documentation/hardware-setup'
    - label: Ubuntu Server Installation
      link: '/documentation/ubuntu-server-installation'
    - label: Hotspot Installation
      link: '/documentation/installation'
    - label: Packages
      link: '/documentation/packages'
    - label: Known Issues
      link: '/documentation/known-issues'
    - label: V4 Nightly Build
      link: '/documentation/v4-nightly-builds'

- label: More
  items:
    - label: Blog Posts
      link: '/blog'
    - label: All Pages
      link: '/pages'
